/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoardCell: typeof import('./src/components/board/BoardCell.vue')['default']
    BoardGrid: typeof import('./src/components/board/BoardGrid.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    GameBoard: typeof import('./src/components/board/GameBoard.vue')['default']
    GameControls: typeof import('./src/components/GameControls.vue')['default']
    GameHeader: typeof import('./src/components/GameHeader.vue')['default']
    GameLayout: typeof import('./src/components/layout/GameLayout.vue')['default']
    GameModal: typeof import('./src/components/game/GameModal.vue')['default']
    GameResult: typeof import('./src/components/game/GameResult.vue')['default']
    GameSettings: typeof import('./src/components/GameSettings.vue')['default']
    GameStats: typeof import('./src/components/GameStats.vue')['default']
    GameTimer: typeof import('./src/components/GameTimer.vue')['default']
    GameTutorial: typeof import('./src/components/GameTutorial.vue')['default']
    InstallPrompt: typeof import('./src/components/InstallPrompt.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    OnlineGame: typeof import('./src/components/OnlineGame.vue')['default']
    OnlineRoomManager: typeof import('./src/components/game/OnlineRoomManager.vue')['default']
    Piece: typeof import('./src/components/board/Piece.vue')['default']
    PlayerCard: typeof import('./src/components/PlayerCard.vue')['default']
    RoomManager: typeof import('./src/components/game/RoomManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SinglePlayerGame: typeof import('./src/components/game/SinglePlayerGame.vue')['default']
    SoundToggle: typeof import('./src/components/welcome/SoundToggle.vue')['default']
    ThemeToggle: typeof import('./src/components/welcome/ThemeToggle.vue')['default']
    UpdatePrompt: typeof import('./src/components/UpdatePrompt.vue')['default']
    VersionInfo: typeof import('./src/components/welcome/VersionInfo.vue')['default']
    WelcomeScreen: typeof import('./src/components/welcome/WelcomeScreen.vue')['default']
  }
}
