/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIGame: typeof import('./components/game/AIGame.vue')['default']
    BoardCell: typeof import('./components/board/BoardCell.vue')['default']
    BoardGrid: typeof import('./components/board/BoardGrid.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    GameBoard: typeof import('./components/board/GameBoard.vue')['default']
    GameControls: typeof import('./components/GameControls.vue')['default']
    GameHeader: typeof import('./components/GameHeader.vue')['default']
    GameHistory: typeof import('./components/game/GameHistory.vue')['default']
    GameLayout: typeof import('./components/layout/GameLayout.vue')['default']
    GameModal: typeof import('./components/game/GameModal.vue')['default']
    GameResult: typeof import('./components/game/GameResult.vue')['default']
    GameSettings: typeof import('./components/GameSettings.vue')['default']
    GameStats: typeof import('./components/GameStats.vue')['default']
    GameTimer: typeof import('./components/GameTimer.vue')['default']
    GameTutorial: typeof import('./components/GameTutorial.vue')['default']
    InstallPrompt: typeof import('./components/InstallPrompt.vue')['default']
    Modal: typeof import('./components/common/Modal.vue')['default']
    OnlineGame: typeof import('./components/OnlineGame.vue')['default']
    OnlineRoomManager: typeof import('./components/game/OnlineRoomManager.vue')['default']
    Piece: typeof import('./components/board/Piece.vue')['default']
    PlayerCard: typeof import('./components/PlayerCard.vue')['default']
    RoomManager: typeof import('./components/game/RoomManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SinglePlayerGame: typeof import('./components/game/SinglePlayerGame.vue')['default']
    SoundToggle: typeof import('./components/welcome/SoundToggle.vue')['default']
    ThemeToggle: typeof import('./components/welcome/ThemeToggle.vue')['default']
    UpdatePrompt: typeof import('./components/UpdatePrompt.vue')['default']
    VersionInfo: typeof import('./components/welcome/VersionInfo.vue')['default']
    WelcomeScreen: typeof import('./components/WelcomeScreen.vue')['default']
  }
}
